title: The Tymscar Blog
email: oscar@tymscar.com
paginate: 1
description: >-
  The place where Tymscar.internalThoughts get copied into the internet.
twitter_username: tymscar
github_username:  tymscar
permalink: pretty

theme: jekyll-theme-poole
plugins:
  - jekyll-feed
  - jemoji
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed


author:
  name: Oscar Monar (Tymscar)
  url: https://twitter.com/tymscar
  email: oscar@tymscar.com

version: 3.0.0

