baseUrl: /
languageCode: en-us
theme: terminal
pagination:
  pagerSize: 5


params:
  # dir name of your blog content (default is `content/posts`)
  contentTypeName: posts
  # ["orange", "blue", "red", "green", "pink"]
  themeColor: blue
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems: 3 
  # show selector to switch language
  showLanguageSelector: false
  # set theme to full screen width
  fullWidthTheme: false
  # center theme with default width
  centerTheme: true
  favicon: "/img/favicon/favicon.ico"
  twitter:
    creator: "tymscar"
    site: "google.com"

markup:
  goldmark:
    renderer:
      unsafe: true

languages:
  en:
    languageName: English
    title: The Tymscar Blog

    params:
      subtitle: brain > /dev/brain
      keywords: "blog tech brain programming nerd linux unix"
      menuMore: Show more
      readMore: Read more
      readOtherPosts: Read other posts

      logo:
        logoText: Tymscar
        logoHomeLink: /
